In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv('dataset.csv')
dataset.head(3)

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision

In [4]:
dataset.iloc[:,10:]

,Age,Fault,PolicyType,VehicleCategory,VehiclePrice,FraudFound_P,PolicyNumber,RepNumber,Deductible,DriverRating,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,21,Policy Holder,Sport - Liability,Sport,more than 69000,0,1,12,300,1,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,34,Policy Holder,Sport - Collision,Sport,more than 69000,0,2,15,400,4,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,47,Policy Holder,Sport - Collision,Sport,more than 69000,0,3,7,400,3,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision
3,65,Third Party,Sedan - Liability,Sport,20000 to 29000,0,4,4,400,2,...,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability
4,27,Third Party,Sport - Collision,Sport,more than 69000,0,5,3,400,1,...,5 years,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15415,35,Policy Holder,Sedan - Collision,Sedan,20000 to 29000,1,15416,5,400,4,...,6 years,31 to 35,No,No,External,none,no change,1 vehicle,1996,Collision
15416,30,Policy Holder,Sedan - Liability,Sport,30000 to 39000,0,15417,11,400,3,...,6 years,31 to 35,No,No,External,more than 5,no change,3 to 4,1996,Liability
15417,24,Policy Holder,Sedan - Collision,Sedan,20000 to 29000,1,15418,4,400,4,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision
15418,34,Third Party,Sedan - All Perils,Sedan,20000 to 29000,0,15419,6,400,4,...,2 years,31 to 35,No,No,External,more than 5,no change,1 vehicle,1996,All Perils
15419,21,Policy Holder,Sedan - Collision,Sedan,20000 to 29000,1,15420,3,400,4,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision

In [5]:
dataset.drop(columns=['PolicyNumber','RepNumber','Year'],inplace=True)

In [6]:
dataset.head(3)

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,PastNumberOfClaims,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,none,3 years,26 to 30,No,No,External,none,1 year,3 to 4,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,none,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,1,7 years,41 to 50,No,No,External,none,no change,1 vehicle,Collision

In [7]:
dataset.columns.tolist()

['Month',
 'WeekOfMonth',
 'DayOfWeek',
 'Make',
 'AccidentArea',
 'DayOfWeekClaimed',
 'MonthClaimed',
 'WeekOfMonthClaimed',
 'Sex',
 'MaritalStatus',
 'Age',
 'Fault',
 'PolicyType',
 'VehicleCategory',
 'VehiclePrice',
 'FraudFound_P',
 'Deductible',
 'DriverRating',
 'Days_Policy_Accident',
 'Days_Policy_Claim',
 'PastNumberOfClaims',
 'AgeOfVehicle',
 'AgeOfPolicyHolder',
 'PoliceReportFiled',
 'WitnessPresent',
 'AgentType',
 'NumberOfSuppliments',
 'AddressChange_Claim',
 'NumberOfCars',
 'BasePolicy']

In [8]:
dataset.isnull().sum()

Month                   0
WeekOfMonth             0
DayOfWeek               0
Make                    0
AccidentArea            0
DayOfWeekClaimed        0
MonthClaimed            0
WeekOfMonthClaimed      0
Sex                     0
MaritalStatus           0
Age                     0
Fault                   0
PolicyType              0
VehicleCategory         0
VehiclePrice            0
FraudFound_P            0
Deductible              0
DriverRating            0
Days_Policy_Accident    0
Days_Policy_Claim       0
PastNumberOfClaims      0
AgeOfVehicle            0
AgeOfPolicyHolder       0
PoliceReportFiled       0
WitnessPresent          0
AgentType               0
NumberOfSuppliments     0
AddressChange_Claim     0
NumberOfCars            0
BasePolicy              0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Drop the single corrupted row containing "0" in claim date fields
dataset = dataset[dataset['DayOfWeekClaimed'] != '0']

# Separate features (x) and target (y)
x = dataset.drop(columns=['FraudFound_P'])
y = dataset['FraudFound_P']

# Perform a stratified train-test split to preserve fraud ratio
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

# Reset index to avoid alignment issues during preprocessing joins
x_train = x_train.reset_index(drop=True)
x_test = x_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

print("Train shape:", x_train.shape)
print("Test shape:", x_test.shape)

Train shape: (12335, 29)
Test shape: (3084, 29)

In [10]:
# Impute missing Age (0 values) to 16 (corresponding to '16 to 17' category)
x_train.loc[x_train['Age'] == 0, 'Age'] = 16
x_test.loc[x_test['Age'] == 0, 'Age'] = 16

# Map binary columns to 0/1
binary_cols = {
    'Sex': {'Male': 1, 'Female': 0},
    'AccidentArea': {'Urban': 1, 'Rural': 0},
    'Fault': {'Policy Holder': 1, 'Third Party': 0},
    'PoliceReportFiled': {'Yes': 1, 'No': 0},
    'WitnessPresent': {'Yes': 1, 'No': 0},
    'AgentType': {'External': 1, 'Internal': 0}
}

for col, mapping in binary_cols.items():
    x_train[col] = x_train[col].map(mapping)
    x_test[col] = x_test[col].map(mapping)

x_train[['Sex', 'AccidentArea', 'Fault', 'PoliceReportFiled', 'WitnessPresent', 'AgentType']].head()

   Sex  AccidentArea  Fault  PoliceReportFiled  WitnessPresent  AgentType
0    1             0      1                  0               0          1
1    1             1      1                  0               0          1
2    1             1      1                  0               0          1
3    1             1      0                  0               0          1
4    1             1      1                  0               0          1

In [11]:
# Map ordinal categorical columns to sequential integers
ordinal_mappings = {
    'VehiclePrice': {
        'less than 20000': 0, '20000 to 29000': 1, '30000 to 39000': 2,
        '40000 to 59000': 3, '60000 to 69000': 4, 'more than 69000': 5
    },
    'AgeOfVehicle': {
        'new': 0, '2 years': 1, '3 years': 2, '4 years': 3,
        '5 years': 4, '6 years': 5, '7 years': 6, 'more than 7': 7
    },
    'AgeOfPolicyHolder': {
        '16 to 17': 0, '18 to 20': 1, '21 to 25': 2, '26 to 30': 3,
        '31 to 35': 4, '36 to 40': 5, '41 to 50': 6, '51 to 65': 7, 'over 65': 8
    },
    'Days_Policy_Accident': {
        'none': 0, '1 to 7': 1, '8 to 15': 2, '15 to 30': 3, 'more than 30': 4
    },
    'Days_Policy_Claim': {
        'none': 0, '8 to 15': 1, '15 to 30': 2, 'more than 30': 3
    },
    'PastNumberOfClaims': {
        'none': 0, '1': 1, '2 to 4': 2, 'more than 4': 3
    },
    'NumberOfSuppliments': {
        'none': 0, '1 to 2': 1, '3 to 5': 2, 'more than 5': 3
    },
    'AddressChange_Claim': {
        'no change': 0, 'under 6 months': 1, '1 year': 2,
        '2 to 3 years': 3, '4 to 8 years': 4
    },
    'NumberOfCars': {
        '1 vehicle': 0, '2 vehicles': 1, '3 to 4': 2,
        '5 to 8': 3, 'more than 8': 4
    }
}

for col, mapping in ordinal_mappings.items():
    x_train[col] = x_train[col].map(mapping)
    x_test[col] = x_test[col].map(mapping)

x_train[list(ordinal_mappings.keys())].head()

,VehiclePrice,AgeOfVehicle,AgeOfPolicyHolder,Days_Policy_Accident,Days_Policy_Claim,PastNumberOfClaims,NumberOfSuppliments,AddressChange_Claim,NumberOfCars
0,1,4,4,4,3,1,0,0,0
1,1,6,5,4,3,2,3,0,0
2,1,5,4,4,3,0,2,0,0
3,1,6,5,4,3,2,3,0,0
4,2,6,5,4,3,3,3,3,1

In [12]:
# One-Hot Encode remaining nominal columns
nominal_cols = ['Make', 'PolicyType', 'MaritalStatus', 'VehicleCategory', 'BasePolicy', 
                'Month', 'MonthClaimed', 'DayOfWeek', 'DayOfWeekClaimed']

# Initialize encoder to drop the first category (to avoid collinearity)
encoder = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')

# Fit only on training set nominal columns
encoder.fit(x_train[nominal_cols])

# Transform both training and testing set nominal columns
train_encoded = encoder.transform(x_train[nominal_cols])
test_encoded = encoder.transform(x_test[nominal_cols])

# Convert to DataFrames
encoded_cols = encoder.get_feature_names_out(nominal_cols)
train_encoded_df = pd.DataFrame(train_encoded, columns=encoded_cols)
test_encoded_df = pd.DataFrame(test_encoded, columns=encoded_cols)

# Drop original nominal columns and join the new one-hot encoded columns
x_train_preprocessed = x_train.drop(columns=nominal_cols).join(train_encoded_df)
x_test_preprocessed = x_test.drop(columns=nominal_cols).join(test_encoded_df)

print("Preprocessed train shape:", x_train_preprocessed.shape)
print("Preprocessed test shape:", x_test_preprocessed.shape)

Preprocessed train shape: (12335, 86)
Preprocessed test shape: (3084, 86)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [14]:
# Train a Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(x_train_preprocessed, y_train)

# Evaluate model predictions
y_pred = rf_model.predict(x_test_preprocessed)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      2899
           1       1.00      0.02      0.03       185

    accuracy                           0.94      3084
   macro avg       0.97      0.51      0.50      3084
weighted avg       0.94      0.94      0.91      3084


Confusion Matrix:
[[2899    0]
 [ 182    3]]

In [16]:
rf_model.score(x_train_preprocessed, y_train),rf_model.score(x_test_preprocessed,y_test)

(0.9998378597486826, 0.9409857328145266)